services:
  nest_db:
    image: mysql:8.0
    container_name: Sequelize_nestjs_mysql_db
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - "3307:3306"
    volumes:
      - Sequelize_nestjs_mysql_data:/var/lib/mysql
    networks:
      - nestjs_network
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: Sequelize_nestjs_phpmyadmin
    environment:    
      PMA_HOST: nest_db
      PMA_PORT: 3306
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASS}
    ports:
      - "8082:80"
    depends_on:
      - nest_db
    networks:
      - nestjs_network


  nest_app:
    image: node:16
    container_name: NestJS_App
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm rebuild bcrypt --build-from-source && npm run start:dev"
    ports:
      - "5000:5000"
    depends_on:
      - nest_db
    networks:
      - nestjs_network


networks:
  nestjs_network:
    driver: bridge

volumes:
  Sequelize_nestjs_mysql_data:
